# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
env:
  - GOPROXY=https://proxy.golang.org,direct
before:
  hooks:
    - make deps
    - make assets
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    main: ./cmd/pgrok/main.go
    id: pgrok
    binary: pgrok
    targets:
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm_6
      - windows_386
      - linux_amd64
      - linux_arm_7
      - linux_arm64
      - linux_386
      - android_arm64
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    main: ./cmd/pgrokd/main.go
    id: pgrokd
    binary: pgrokd
    targets:
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm_7
      - windows_386
      - linux_amd64
      - linux_arm_7
      - linux_arm64
      - linux_386
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
archives:
  - id: pgrokd
    builds:
      - pgrokd
    name_template: "pgrokd_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
#     replacements:
#       darwin: MacOS
#       linux: Linux
#       windows: Windows
#       386: i386
#       amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
  - id: pgrok
    builds:
      - pgrok
    name_template: "pgrok_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
#     replacements:
#       darwin: MacOS
#       linux: Linux
#       windows: Windows
#       386: i386
#       amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
# brews:
#   - name: pgrok
#     ids:
#       - pgrok
#     tap:
#       owner: jerson
#       name: homebrew-tap
#     commit_author:
#       name: Gerson Alexander Pardo Gamez
#       email: jeral17@gmail.com
#     folder: Formula
#     homepage: "https://github.com/jerson/pgrok"
#     description: "Introspected tunnels to localhost a fork from pgrok."
#     install: |
#       bin.install "pgrok"
#     test: |
#       system "#{bin}/pgrok", "-v"
#   - name: pgrokd
#     ids:
#       - pgrokd
#     tap:
#       owner: jerson
#       name: homebrew-tap
#     commit_author:
#       name: Gerson Alexander Pardo Gamez
#       email: jeral17@gmail.com
#     folder: Formula
#     homepage: "https://github.com/jerson/pgrok"
#     description: "Server introspected tunnels to localhost a fork from pgrok."
#     install: |
#       bin.install "pgrokd"
#     test: |
#       system "#{bin}/pgrokd", "-v"
# scoop:
#   bucket:
#     owner: jerson
#     name: scoop-bucket
#   commit_author:
#     name: Gerson Alexander Pardo Gamez
#     email: jeral17@gmail.com
#   homepage: "https://github.com/jerson/pgrok"
#   description: "Introspected tunnels to localhost a fork from pgrok."
#   license: MIT
# nfpms:
#   - id: pgrok
#     homepage: "https://github.com/jerson/pgrok"
#     description: "Introspected tunnels to localhost a fork from pgrok."
#     maintainer: Gerson Alexander Pardo Gamez <jeral17@gmail.com>
#     license: MIT
#     formats:
#       - deb
#       - rpm
#     recommends:
#       - rpm
#     builds:
#       - pgrok
#       - pgrokd
